image: node:10.15.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - npm i -S hexo-prism-plugin
  - npm install hexo-generator-search --save
  - npm i --save hexo-wordcount
  - npm i hexo-permalink-pinyin --save
  - hexo clean
  - hexo generate
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master