image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install -g create-next-app@0.6.4
  - npm i -S hexo-prism-plugin
  - npm install hexo-generator-search --save
  - npm i --save hexo-wordcount
  - npm i hexo-permalink-pinyin --save
  - hexo clean
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master