image: node:8.11.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - npm uninstall hexo-generator-index --save
  - npm install hexo-generator-index-pin-top --save
  - npm install hexo-generator-searchdb --save
  - npm i --save hexo-wordcount
  - hexo clean
  - hexo generate
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master